export const CALENDAR_LAYOUT = Object.freeze({
  MONTH_WINDOW_RADIUS: 50,
  MONTH_RENDER_NEIGHBORS: 1,
  MEASURE_DELTA_EPSILON: 0.5,
  HEADER_LAYOUT_MIN_RATIO: 0.6,
});

export const CALENDAR_GESTURE = Object.freeze({
  SNAP_PROGRESS_THRESHOLD: 0.5,
  SNAP_VELOCITY_Y: 450,
  COLLAPSED_PROGRESS_THRESHOLD: 0.99,
  COLLAPSED_SET_THRESHOLD: 0.9,
  EXPANDED_SET_THRESHOLD: 0.1,
  MONTH_COLLAPSE_PHASE_SPLIT: 0.5,
  SNAP_SPRING_DAMPING: 22,
  SNAP_SPRING_STIFFNESS: 220,
  SNAP_SPRING_MASS: 0.9,
  SNAP_SPRING_OVERSHOOT_CLAMPING: true,
  SNAP_SPRING_REST_SPEED_THRESHOLD: 12,
  SNAP_SPRING_REST_DISPLACEMENT_THRESHOLD: 0.5,
  SNAP_INPUT_VELOCITY_MAX: 1800,
  MONTH_SWIPE_VELOCITY_X: 450,
  MONTH_SWIPE_DISTANCE_RATIO: 0.2,
  MONTH_SWIPE_DIRECTION_RATIO: 1.2,
  MONTH_SWIPE_VELOCITY_DIRECTION_RATIO: 1.1,
});
