export const CALENDAR_LAYOUT = Object.freeze({
  MONTH_WINDOW_RADIUS: 50,
  FIXED_WEEK_ROWS: 6,
});

export const CALENDAR_GESTURE = Object.freeze({
  SNAP_PROGRESS_THRESHOLD: 0.5,
  SNAP_VELOCITY_Y: 450,
  COLLAPSED_PROGRESS_THRESHOLD: 0.99,
  COLLAPSED_SET_THRESHOLD: 0.9,
  EXPANDED_SET_THRESHOLD: 0.1,
  MONTH_COLLAPSE_PHASE_SPLIT: 0.5,
  SNAP_SPRING_DAMPING: 22,
  SNAP_SPRING_STIFFNESS: 220,
  SNAP_SPRING_MASS: 0.9,
});
