DO $$
DECLARE
  stmts text[] := ARRAY[
    'DROP POLICY IF EXISTS _backup_profiles_policies_select_admins ON public._backup_profiles_policies; CREATE POLICY _backup_profiles_policies_select_admins ON public._backup_profiles_policies FOR SELECT TO authenticated USING (is_admin_or_dispatcher());',
    'DROP POLICY IF EXISTS app_admins_delete ON public.app_admins; CREATE POLICY app_admins_delete ON public.app_admins FOR DELETE TO authenticated USING (is_admin_or_dispatcher());',
    'DROP POLICY IF EXISTS app_admins_insert ON public.app_admins; CREATE POLICY app_admins_insert ON public.app_admins FOR INSERT TO authenticated WITH CHECK (is_admin_or_dispatcher());',
    'DROP POLICY IF EXISTS app_admins_select ON public.app_admins; CREATE POLICY app_admins_select ON public.app_admins FOR SELECT TO authenticated USING (is_admin_or_dispatcher());',
    'DROP POLICY IF EXISTS app_admins_update ON public.app_admins; CREATE POLICY app_admins_update ON public.app_admins FOR UPDATE TO authenticated USING (is_admin_or_dispatcher()) WITH CHECK (is_admin_or_dispatcher());',
    'DROP POLICY IF EXISTS app_audit_log_delete_any ON public.app_audit_log; CREATE POLICY app_audit_log_delete_any ON public.app_audit_log FOR DELETE TO service_role USING (true);',
    'DROP POLICY IF EXISTS app_audit_log_insert_any ON public.app_audit_log; CREATE POLICY app_audit_log_insert_any ON public.app_audit_log FOR INSERT TO service_role WITH CHECK (true);',
    'DROP POLICY IF EXISTS app_audit_log_select_service ON public.app_audit_log; CREATE POLICY app_audit_log_select_service ON public.app_audit_log FOR SELECT TO service_role USING (true);',
    'DROP POLICY IF EXISTS app_audit_log_update_any ON public.app_audit_log; CREATE POLICY app_audit_log_update_any ON public.app_audit_log FOR UPDATE TO service_role USING (true) WITH CHECK (true);',
    -- Policies for dropped legacy tables removed (`app_company_settings`, `app_enabled_fields`)
    -- Policies for dropped legacy table `app_field_visibility` removed
    'DROP POLICY IF EXISTS app_role_permissions_select_company ON public.app_role_permissions; CREATE POLICY app_role_permissions_select_company ON public.app_role_permissions FOR SELECT TO authenticated USING ((company_id = user_company_id()));',
    'DROP POLICY IF EXISTS app_role_permissions_insert_admin_only ON public.app_role_permissions; CREATE POLICY app_role_permissions_insert_admin_only ON public.app_role_permissions FOR INSERT TO authenticated WITH CHECK ((is_admin() AND (company_id = user_company_id())));',
    'DROP POLICY IF EXISTS app_role_permissions_update_admin_only ON public.app_role_permissions; CREATE POLICY app_role_permissions_update_admin_only ON public.app_role_permissions FOR UPDATE TO authenticated USING ((is_admin() AND (company_id = user_company_id()))) WITH CHECK ((is_admin() AND (company_id = user_company_id())));',
    'DROP POLICY IF EXISTS app_role_permissions_delete_admin_only ON public.app_role_permissions; CREATE POLICY app_role_permissions_delete_admin_only ON public.app_role_permissions FOR DELETE TO authenticated USING ((is_admin() AND (company_id = user_company_id())));',
    'DROP POLICY IF EXISTS "Admins can update their company" ON public.companies; CREATE POLICY "Admins can update their company" ON public.companies FOR UPDATE TO public USING ((id IN ( SELECT profiles.company_id FROM profiles WHERE ((profiles.id = auth.uid()) AND (profiles.role = ''admin''::text)))));',
    'DROP POLICY IF EXISTS "Users can create companies" ON public.companies; CREATE POLICY "Users can create companies" ON public.companies FOR INSERT TO public WITH CHECK (true);',
    'DROP POLICY IF EXISTS "Users can view their company" ON public.companies; CREATE POLICY "Users can view their company" ON public.companies FOR SELECT TO public USING ((id IN ( SELECT profiles.company_id FROM profiles WHERE (profiles.id = auth.uid()))));',
    'DROP POLICY IF EXISTS "companies tz select same company" ON public.companies; CREATE POLICY "companies tz select same company" ON public.companies FOR SELECT TO authenticated USING ((id = user_company_id()));',
    'DROP POLICY IF EXISTS "companies tz update by company admin" ON public.companies; CREATE POLICY "companies tz update by company admin" ON public.companies FOR UPDATE TO authenticated USING ((is_admin() AND (id = user_company_id()))) WITH CHECK ((is_admin() AND (id = user_company_id())));',
    'DROP POLICY IF EXISTS compensation_overrides_delete ON public.compensation_overrides; CREATE POLICY compensation_overrides_delete ON public.compensation_overrides FOR DELETE TO authenticated USING ((company_id = user_company_id()) AND is_admin_or_dispatcher());',
    'DROP POLICY IF EXISTS compensation_overrides_insert ON public.compensation_overrides; CREATE POLICY compensation_overrides_insert ON public.compensation_overrides FOR INSERT TO authenticated WITH CHECK ((company_id = user_company_id()) AND is_admin_or_dispatcher());',
    'DROP POLICY IF EXISTS compensation_overrides_select ON public.compensation_overrides; CREATE POLICY compensation_overrides_select ON public.compensation_overrides FOR SELECT TO authenticated USING ((company_id = user_company_id()) AND is_admin_or_dispatcher());',
    'DROP POLICY IF EXISTS compensation_overrides_update ON public.compensation_overrides; CREATE POLICY compensation_overrides_update ON public.compensation_overrides FOR UPDATE TO authenticated USING (((company_id = user_company_id()) AND is_admin_or_dispatcher())) WITH CHECK ((company_id = user_company_id()) AND is_admin_or_dispatcher());',
    'DROP POLICY IF EXISTS compensation_rules_select_admins ON public.compensation_rules; CREATE POLICY compensation_rules_select_admins ON public.compensation_rules FOR SELECT TO authenticated USING ((company_id = user_company_id()) AND is_admin_or_dispatcher());',
    'DROP POLICY IF EXISTS crew_members_select_own ON public.crew_members; CREATE POLICY crew_members_select_own ON public.crew_members FOR SELECT TO authenticated USING ((user_id = app_uid()));',
    'DROP POLICY IF EXISTS crews_delete_any ON public.crews; CREATE POLICY crews_delete_any ON public.crews FOR DELETE TO authenticated USING ((company_id = user_company_id()) AND is_admin_or_dispatcher());',
    'DROP POLICY IF EXISTS crews_insert_any ON public.crews; CREATE POLICY crews_insert_any ON public.crews FOR INSERT TO authenticated WITH CHECK ((company_id = user_company_id()) AND is_admin_or_dispatcher());',
    'DROP POLICY IF EXISTS crews_select_any ON public.crews; CREATE POLICY crews_select_any ON public.crews FOR SELECT TO authenticated USING ((company_id = user_company_id()) AND is_admin_or_dispatcher());',
    'DROP POLICY IF EXISTS crews_update_any ON public.crews; CREATE POLICY crews_update_any ON public.crews FOR UPDATE TO authenticated USING (((company_id = user_company_id()) AND is_admin_or_dispatcher())) WITH CHECK ((company_id = user_company_id()));',
    'DROP POLICY IF EXISTS departments_delete_admin_dispatcher ON public.departments; CREATE POLICY departments_delete_admin_dispatcher ON public.departments FOR DELETE TO authenticated USING (((company_id = user_company_id()) AND is_admin_or_dispatcher()));',
    'DROP POLICY IF EXISTS departments_insert_admin_dispatcher ON public.departments; CREATE POLICY departments_insert_admin_dispatcher ON public.departments FOR INSERT TO authenticated WITH CHECK (((company_id = user_company_id()) AND is_admin_or_dispatcher()));',
    'DROP POLICY IF EXISTS departments_select_company ON public.departments; CREATE POLICY departments_select_company ON public.departments FOR SELECT TO authenticated USING ((company_id = user_company_id()));',
    'DROP POLICY IF EXISTS departments_update_admin_dispatcher ON public.departments; CREATE POLICY departments_update_admin_dispatcher ON public.departments FOR UPDATE TO authenticated USING (((company_id = user_company_id()) AND is_admin_or_dispatcher())) WITH CHECK (((company_id = user_company_id()) AND is_admin_or_dispatcher()));',
    'DROP POLICY IF EXISTS error_logs_insert_any ON public.error_logs; CREATE POLICY error_logs_insert_any ON public.error_logs FOR INSERT TO authenticated WITH CHECK ((user_id = app_uid()));',
    'DROP POLICY IF EXISTS error_logs_select_own ON public.error_logs; CREATE POLICY error_logs_select_own ON public.error_logs FOR SELECT TO authenticated USING ((user_id = app_uid()));',
    'DROP POLICY IF EXISTS events_insert_any ON public.events; CREATE POLICY events_insert_any ON public.events FOR INSERT TO authenticated WITH CHECK ((user_id = app_uid()));',
    'DROP POLICY IF EXISTS events_select_own ON public.events; CREATE POLICY events_select_own ON public.events FOR SELECT TO authenticated USING ((user_id = app_uid()));',
    'DROP POLICY IF EXISTS "allow insert feedbacks for authenticated" ON public.feedbacks; CREATE POLICY "allow insert feedbacks for authenticated" ON public.feedbacks FOR INSERT TO authenticated WITH CHECK ((user_id = app_uid()));',
    'DROP POLICY IF EXISTS feedbacks_select_own ON public.feedbacks; CREATE POLICY feedbacks_select_own ON public.feedbacks FOR SELECT TO authenticated USING ((user_id = app_uid()));',
    'DROP POLICY IF EXISTS notification_prefs_insert_own ON public.notification_prefs; CREATE POLICY notification_prefs_insert_own ON public.notification_prefs FOR INSERT TO authenticated WITH CHECK ((user_id = app_uid()));',
    'DROP POLICY IF EXISTS notification_prefs_select_own ON public.notification_prefs; CREATE POLICY notification_prefs_select_own ON public.notification_prefs FOR SELECT TO authenticated USING (is_self(user_id));',
    'DROP POLICY IF EXISTS notification_prefs_update_own ON public.notification_prefs; CREATE POLICY notification_prefs_update_own ON public.notification_prefs FOR UPDATE TO authenticated USING (is_self(user_id)) WITH CHECK (is_self(user_id));',
    'DROP POLICY IF EXISTS order_payouts_cache_select_admins ON public.order_payouts_cache; CREATE POLICY order_payouts_cache_select_admins ON public.order_payouts_cache FOR SELECT TO authenticated USING ((company_id = user_company_id()) AND is_admin_or_dispatcher());',
    'DROP POLICY IF EXISTS orders_delete_admin_dispatcher ON public.orders; CREATE POLICY orders_delete_admin_dispatcher ON public.orders FOR DELETE TO authenticated USING ((company_id = user_company_id()) AND is_admin_or_dispatcher());',
    'DROP POLICY IF EXISTS orders_insert_admin_dispatcher ON public.orders; CREATE POLICY orders_insert_admin_dispatcher ON public.orders FOR INSERT TO authenticated WITH CHECK ((is_admin_or_dispatcher() AND (company_id = user_company_id()) AND department_belongs_to_company(department_id, user_company_id())));',
    'DROP POLICY IF EXISTS orders_select_combined ON public.orders; CREATE POLICY orders_select_combined ON public.orders FOR SELECT TO authenticated USING (((is_admin_or_dispatcher() AND (company_id = user_company_id())) OR ((assigned_to = current_user_id()) AND (company_id = user_company_id()))));',
    'DROP POLICY IF EXISTS orders_update_combined ON public.orders; CREATE POLICY orders_update_combined ON public.orders FOR UPDATE TO authenticated USING (((is_admin_or_dispatcher() AND (company_id = user_company_id())) OR (user_is_worker_in_company(company_id) AND (assigned_to = current_user_id())) OR ((assigned_to = current_user_id()) AND (company_id = user_company_id())))) WITH CHECK (((is_admin_or_dispatcher() AND (company_id = user_company_id())) OR (user_is_worker_in_company(company_id) AND (assigned_to = current_user_id())) OR ((assigned_to = current_user_id()) AND (company_id = user_company_id()))));',
    'DROP POLICY IF EXISTS insert_own_profile ON public.profiles; CREATE POLICY insert_own_profile ON public.profiles FOR INSERT TO authenticated WITH CHECK ((id = ( SELECT auth.uid() AS uid)));',
    'DROP POLICY IF EXISTS profiles_update_own ON public.profiles; CREATE POLICY profiles_update_own ON public.profiles FOR UPDATE TO authenticated USING ((id = ( SELECT auth.uid() AS uid))) WITH CHECK ((id = ( SELECT auth.uid() AS uid)));',
    'DROP POLICY IF EXISTS profiles_update_admin ON public.profiles; CREATE POLICY profiles_update_admin ON public.profiles FOR UPDATE TO authenticated USING ((is_admin_or_dispatcher() AND (company_id = user_company_id()))) WITH CHECK ((is_admin_or_dispatcher() AND (company_id = user_company_id())));',
    'DROP POLICY IF EXISTS select_profiles_all ON public.profiles; CREATE POLICY select_profiles_all ON public.profiles FOR SELECT TO authenticated USING (true);',
    'DROP POLICY IF EXISTS push_tokens_delete_own ON public.push_tokens; CREATE POLICY push_tokens_delete_own ON public.push_tokens FOR DELETE TO authenticated USING (is_self(user_id));',
    'DROP POLICY IF EXISTS push_tokens_insert_own ON public.push_tokens; CREATE POLICY push_tokens_insert_own ON public.push_tokens FOR INSERT TO authenticated WITH CHECK ((user_id = app_uid()));',
    'DROP POLICY IF EXISTS push_tokens_select_own ON public.push_tokens; CREATE POLICY push_tokens_select_own ON public.push_tokens FOR SELECT TO authenticated USING (is_self(user_id));',
    'DROP POLICY IF EXISTS work_types_select_admins ON public.work_types; CREATE POLICY work_types_select_admins ON public.work_types FOR SELECT TO authenticated USING ((company_id = user_company_id()) AND is_admin_or_dispatcher());',
    'DROP POLICY IF EXISTS work_types_insert_admins ON public.work_types; CREATE POLICY work_types_insert_admins ON public.work_types FOR INSERT TO authenticated WITH CHECK ((company_id = user_company_id()) AND is_admin_or_dispatcher());',
    'DROP POLICY IF EXISTS work_types_update_admins ON public.work_types; CREATE POLICY work_types_update_admins ON public.work_types FOR UPDATE TO authenticated USING ((company_id = user_company_id()) AND is_admin_or_dispatcher()) WITH CHECK ((company_id = user_company_id()) AND is_admin_or_dispatcher());',
    'DROP POLICY IF EXISTS work_types_delete_admins ON public.work_types; CREATE POLICY work_types_delete_admins ON public.work_types FOR DELETE TO authenticated USING ((company_id = user_company_id()) AND is_admin_or_dispatcher());'
  ];
  s text;
BEGIN
  FOREACH s IN ARRAY stmts LOOP
    EXECUTE s;
  END LOOP;
END $$;
