begin;

create table if not exists public.support_push_receipts (
  id bigint generated by default as identity primary key,
  notification_event_id bigint not null
    references public.notification_events(id) on delete cascade,
  recipient_user_id uuid not null
    references auth.users(id) on delete cascade,
  push_token text not null,
  ticket_id text not null unique,
  status text not null default 'pending'
    check (status in ('pending', 'delivered', 'error')),
  check_count integer not null default 0
    check (check_count >= 0),
  available_at timestamptz not null default (now() + interval '15 minutes'),
  checked_at timestamptz,
  provider_error text,
  provider_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists support_push_receipts_pending_idx
  on public.support_push_receipts (available_at, id)
  where status = 'pending';

create index if not exists support_push_receipts_event_idx
  on public.support_push_receipts (notification_event_id, id);

alter table public.support_push_receipts enable row level security;

revoke all on table public.support_push_receipts from public, anon, authenticated;
grant select, insert, update, delete on table public.support_push_receipts to service_role;

revoke all on sequence public.support_push_receipts_id_seq from public, anon, authenticated;
grant usage, select on sequence public.support_push_receipts_id_seq to service_role;

commit;
