create table if not exists public.object_media_external_map (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  object_id uuid not null references public.client_objects(id) on delete cascade,
  category text not null check (category in ('media_file_1', 'media_file_2', 'media_file_3')),
  provider text not null check (provider in ('beget_s3', 'yandex_disk')),
  source_url text not null,
  external_path text not null,
  display_url text,
  display_url_updated_at timestamptz,
  file_size_bytes bigint not null default 0,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (object_id, category, source_url)
);

create index if not exists idx_object_media_external_map_object_category
  on public.object_media_external_map (object_id, category);

create index if not exists idx_object_media_external_map_company_source
  on public.object_media_external_map (company_id, source_url);

alter table public.object_media_external_map enable row level security;

revoke all on public.object_media_external_map from anon, authenticated;
grant select, insert, update, delete on public.object_media_external_map to service_role;
grant usage, select on sequence public.object_media_external_map_id_seq to service_role;

create trigger trg_object_media_external_map_set_updated_at
before update on public.object_media_external_map
for each row execute function public.set_updated_at();
